### ISSUE TITLE
Numix-based themes and mate-dock-applet

### ISSUE THREAD

**Issue by cellularlupus** [themix-project/oomox-gtk-theme#62]
In versions of oomox newer than 1.6.0, the mate-dock-applet uses the background color for windows rather than the mate-panel background color when using numix-based themes. 

Here's a screenshot of the mate-dock-applet with a numix-based theme exported from oomox 1.6.0
![omoox 1 6 0](https://user-images.githubusercontent.com/38230298/50122553-0d35f500-022b-11e9-8d68-2a11d408bda5.png)

and here's a screenshot of the mate-dock-applet with a numix-based theme exported from oomox 1.6.2
![oomox 1 6 2](https://user-images.githubusercontent.com/38230298/50122578-38204900-022b-11e9-9bf9-33426b353604.png)

I've tried enabling the "change panel color to match wallpaper" and "change color of dock's panel only" settings in the mate-dock-applet's preferences to see if that makes a difference, but the background remains the same. 

mate-dock-applet is version 0.87
mate-desktop is version 1.20.3
i'm using ubuntu 18.10

**Comment by cellularlupus** [comment]
doing that doesnt seem to have an effect on anything

**Comment by actionless** [comment]
`MatePanelAppletFrameDBus viewport`?

**Comment by cellularlupus** [comment]
still nothing

**Comment by actionless** [comment]
```
PanelToplevel viewport {
background-color: #00ff00;
}
``` ?

**Comment by actionless** [comment]
weird, mb try pause and unpause css override?

**Comment by cellularlupus** [comment]
i've also tried that

**Comment by actionless** [comment]
and if you add all those snippets to ~/.config/gtk-3.0/gtk.css instead of inspector?
it seems gtk inspector works somehow weirdly with that panel

**Comment by nana-4** [comment]
I can reproduce this. Here's CSS Selector in my GTK+ Inspector when selecting the white background:

![image](https://user-images.githubusercontent.com/9556384/50240494-51cab780-0408-11e9-96dd-4b8e484c424d.png)

(Actually `viewport` has the `background-color`, not `grid`.)

As you can see from the screenshot, 85bbd12d71cb85ae0e7a45a4af6c0a75ecc6f940 does not fix this, unfortunately.

FYI, most other themes (including Numix, Adwaita, Materia, Arc, etc.) don't have `background-color` in `viewport`. I wonder if you can remove that definition from the theme.

**Comment by actionless** [comment]
@nana-4 

and if applying 

```scss
#PanelApplet viewport {
background-color: #00ff00;
}
```

or 

```scss
PanelApplet viewport {
background-color: #00ff00;
}
```

makes any difference?

**Comment by actionless** [comment]
@nana-4 about background-color:
i've double checked against Arc and Adwaita -- you right, instead of styling `viewport` itself they styling `viewport frame`

i'll change it in the same way then

**Comment by actionless** [comment]
please check now:

[oomox_1.7.2.3-11-g10088793_17.04+.deb.gz](https://github.com/themix-project/oomox-gtk-theme/files/2696264/oomox_1.7.2.3-11-g10088793_17.04%2B.deb.gz)


[oomox_1.7.2.3-11-g10088793_18.10+.deb.gz](https://github.com/themix-project/oomox-gtk-theme/files/2696265/oomox_1.7.2.3-11-g10088793_18.10%2B.deb.gz)

**Comment by cellularlupus** [comment]
that fixed it, thanks

**Comment by actionless** [comment]
:fireworks:

**Comment by nana-4** [comment]
@actionless 

> makes any difference?

Yeah, both of them change the `background-color` as expected.

> btw Materia is not styling it and idk if it's purposely or not

Actually Materia also has that style ([for example](https://github.com/nana-4/materia-theme/blob/master/src/_sass/gtk/_common-3.20.scss#L2674)) as well as Adwaita and Arc :wink: 

FYI, all those themes are only styling `border-style: none` in `viewport.frame`, but not having `background-color`, `color` and `border` styles.

Just out of curiosity, for what did you style `background-color`, etc. in `viewport`?
Perhaps there is more appropriate styling than 9034c4236b8cf48203749cdb11ff442fc7ac22b2.

**Comment by actionless** [comment]
as an example you can open `gradio` app and compare it across the named themes

**Comment by nana-4** [comment]
I see. It seems `gradio` app has [`.content-view`](https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss#L4341) style class to change the background-color. This is why Adwaita and Arc change the background-color and Materia doesn't.

I'd recommend you style those colors with `.content-view` instead of 9034c42.
Since `notebook scrolledwindow viewport,
    :not(notebook) scrolledwindow viewport frame` are still quite common, other unexpected styles may happen with another apps/components.

**Comment by actionless** [comment]
sure thing, thanks for your investigation!
