### ISSUE TITLE
Arc theme for GTK 3.2x missing?

### ISSUE THREAD

**Issue by thewaiter** [themix-project/oomox-gtk-theme#65]
Hello there

Today I tried to play with arc theme I like to use for Bodhi next release and I had noticed the GTK 3.20 theme is not generated. Have I missed something or this feature is not supported yet?

Thanx

**Comment by actionless** [comment]
it just being generated in gtk-3.0 dir but works fine

if you have any more questions on that please contact Arc theme maintainers
