### ISSUE TITLE
Cinnamox-Kashmir-blue

### ISSUE THREAD

**Issue by dave841** [themix-project/oomox-gtk-theme#68]
got a bit of problem with the update it said that the problem was not installing right and could not install, the boot up of my cinnamon was fine but not sure what the problem is did not say.

**Comment by actionless** [comment]
CC @smurphos

**Comment by smurphos** [comment]
Hi @dave841,

I'm not sure what your issue is? If it's with updating the Kashmir Blue theme from within Cinnamon's interface you need to report it here https://github.com/linuxmint/cinnamon-spices-themes
