### ISSUE TITLE
Found your april fools day timebomb

### ISSUE THREAD

**Issue by glohkamp** [themix-project/oomox-gtk-theme#74]
if [[ $(date +"%m%d") = "0401" ]] && [[ -z "${no_jokes:-}" ]] ; then
	echo -e "\n\nError patching uxtheme.dll\n\n"
	ACCENT_BG=30a55c BG=ECE9D8 BTN_BG=f8f8f8 BTN_FG=000000
	BTN_OUTLINE_OFFSET=-3 BTN_OUTLINE_WIDTH=1 FG=000000 GRADIENT=0.08
	GTK3_GENERATE_DARK=False HDR_BTN_BG=f8f8f8 HDR_BTN_FG=000000 HDR_BG=ECE9D8
	HDR_FG=000000 OUTLINE_WIDTH=1 ROUNDNESS=3 SEL_BG=3169C6 SEL_FG=FFFFFF
	SPACING=3 TXT_BG=FFFFFF TXT_FG=000000 WM_BORDER_FOCUS=3169C6 WM_BORDER_UNFOCUS=ECE9D8
fi

was more frustrating than funny

**Comment by actionless** [comment]
good to know

**Comment by DziubanMaciej** [comment]
Found it today. Frustrating, but kind of funny to me.
