### ISSUE TITLE
memory leak when exporting.

### ISSUE THREAD

**Issue by coreybruce** [themix-project/oomox-gtk-theme#78]
Hi just want to report that Themix when exporting materia themes and will be stuck in exporting limbo and will memory leak using all your available ram.

Exporting Numix based themes for example work fine without issues.

OS: Manjaro xfce4

**Comment by actionless** [comment]
i can't even guess what's wrong with your setup as you provided zero information, but on arch it's working

<s>they recently added user-friendly installer, so no need anymore to use arch linux from ali express :)</s>

**Comment by coreybruce** [comment]
Sorry, I wasn't sure what information you would need. I just wanted to get the conversation on the report going first. :P

**Comment by actionless** [comment]
ah, my bad i've just woke up and read wrong this line i original message:

> Exporting Numix based themes for example work fine without issues.

this is repo for numix-based theme

**Comment by coreybruce** [comment]
So this is only for numix themes? Why does it still support material themes than?

**Comment by actionless** [comment]
materia repo is elsewhere
