### ISSUE TITLE
themix-theme-oomox-git package requires gtk2

### ISSUE THREAD

**Issue by SArpnt** [themix-project/oomox-gtk-theme#91]
i don't have any actual programs that use gtk2, so i don't need to theme it, but the themix-theme-oomox-git package requires gtk-engine-murrine and gtk-engines, which both require gtk2. i would rather just be able to uninstall gtk2, even if it means i can't generate a gtk2 theme.

**Comment by actionless** [comment]
does the theme generation still works if you install the package without gtk2 dep by editing its pkgbuild?

**Comment by SArpnt** [comment]
i uninstalled gtk-engine-murraine, gtk-engines, gtk2, and all the dependencies of gtk2. there were no errors generating the theme and it looks like it works perfectly fine in gtk3 and the color scheme for qt*ct is correct. i'm not sure if the generated theme works for gtk2 or if it would display correctly without the two gtk engine packages, but the program never indicated that it was generated incorrectly.

**Comment by actionless** [comment]
thanks for checking, i'll move it to optional deps then 👍
